Add missing `feedback` parameter (#19)
WARNING    Traceback (most recent call last):
              File "/home/mkuhn/.local/share/QGIS/QGIS3/profiles/default/python/plugins/swiss_locator/swiss_locator_filter.py", line 404, in reply_finished
              self.handle_response(response, search, feedback)
             TypeError: handle_response() missing 1 required positional argument: 'feedback'